version: 2
updates:

# branch - master
- package-ecosystem: "maven"
  directory: "/"
  target-branch: "master"
  schedule: 
    interval: "weekly"

# branch - v1.x
- package-ecosystem: "maven"
  directory: "/"
  target-branch: "v1.x"
  schedule:
    interval: "weekly"

